---
- name: Playbook to install apache2 and mysql
  hosts: webservers
  become: yes

  vars:
    env: null  

  vars_files:
    - "../props.yml"

  tasks:
    - name: install apache
      apt: name=apache2 state=installed

    - name: install php
      apt: name={{item}} state=installed
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql

    - name: copy files
      template: src={{ item }} dest=/var/www/html/{{ item | basename }}
      with_fileglob:
        - "{{ version }}/files/*"

    - name: copy www_templates
      template: src={{ item }} dest=/var/www/html/{{ item | basename | regex_replace('.j2','') }}
      with_fileglob:
        - {{ version }}/templates/www/*.j2

    - name: copy conf_templates
      template: src={{ item }} dest=/etc/apache2/{{ item | basename | regex_replace('.j2','') }}
      with_fileglob:
        - "{{ version }}/templates/conf/*.j2"
      notify: restart apache2


  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
